// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa.Infrastructure.Data;

#nullable disable

namespace Villa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214100133_seedingthedata")]
    partial class seedingthedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa.Domain.Entities.Villia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSwimmingPool")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 1, 32, 707, DateTimeKind.Utc).AddTicks(987),
                            Description = "A beautiful villa with stunning ocean views.",
                            HasSwimmingPool = true,
                            ImageUrl = "https://example.com/images/oceanview_retreat.jpg",
                            Location = "Malibu, CA",
                            Name = "Oceanview Retreat",
                            NumberOfBathrooms = 3,
                            NumberOfBedrooms = 4,
                            PricePerNight = 750.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 1, 32, 707, DateTimeKind.Utc).AddTicks(1079),
                            Description = "Cozy villa nestled in the mountains, perfect for a winter getaway.",
                            HasSwimmingPool = false,
                            ImageUrl = "https://example.com/images/mountain_escape.jpg",
                            Location = "Aspen, CO",
                            Name = "Mountain Escape",
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 3,
                            PricePerNight = 600.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 1, 32, 707, DateTimeKind.Utc).AddTicks(1081),
                            Description = "Modern villa located in the heart of the city with breathtaking skyline views.",
                            HasSwimmingPool = false,
                            ImageUrl = "https://example.com/images/city_lights_villa.jpg",
                            Location = "New York, NY",
                            Name = "City Lights Villa",
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 2,
                            PricePerNight = 850.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
