// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa.Infrastructure.Data;

#nullable disable

namespace Villa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216230239_AddedVillaNumbermodel")]
    partial class AddedVillaNumbermodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 101,
                            SpecialDetails = "Ocean view from every room.",
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 102,
                            SpecialDetails = "Private beach access.",
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 201,
                            SpecialDetails = "Fireplace and ski-in/ski-out access.",
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 202,
                            SpecialDetails = "Hot tub with mountain views.",
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 301,
                            SpecialDetails = "Rooftop terrace with city skyline views.",
                            VillaId = 3
                        },
                        new
                        {
                            VillaNo = 302,
                            SpecialDetails = "Close to major attractions and nightlife.",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("Villa.Domain.Entities.Villia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSwimmingPool")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beautiful villa with stunning ocean views.",
                            HasSwimmingPool = true,
                            ImageUrl = "https://example.com/images/oceanview_retreat.jpg",
                            Location = "Malibu, CA",
                            Name = "Oceanview Retreat",
                            NumberOfBathrooms = 3,
                            NumberOfBedrooms = 4,
                            PricePerNight = 750.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cozy villa nestled in the mountains, perfect for a winter getaway.",
                            HasSwimmingPool = false,
                            ImageUrl = "https://example.com/images/mountain_escape.jpg",
                            Location = "Aspen, CO",
                            Name = "Mountain Escape",
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 3,
                            PricePerNight = 600.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern villa located in the heart of the city with breathtaking skyline views.",
                            HasSwimmingPool = false,
                            ImageUrl = "https://example.com/images/city_lights_villa.jpg",
                            Location = "New York, NY",
                            Name = "City Lights Villa",
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 2,
                            PricePerNight = 850.00m
                        });
                });

            modelBuilder.Entity("Villa.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("Villa.Domain.Entities.Villia", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
